config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root "articles#index"
  devise_for :users

  get "up" => "rails/health#show", as: :rails_health_check

  resources :articles do
    resources :comments
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  # def initialize(user)
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  # end
  def initialize(user)
    user ||= User.new

    if user.has_role?(:admin)
      can :manage, :all
    elsif user.has_role?(:author)
      can [:read, :create], Article
      can [:update, :destroy], Article, user_id: user.id
      can [:read, :create], Comment
      can [:update, :destroy], Comment, user_id: user.id
    else
      can :read, :all
      can :create, Comment
      can [:update, :destroy], Comment, user_id: user.id
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  def self.ransackable_attributes(auth_object = nil)
    column_names + _ransackers.keys
  end

  def self.ransackable_associations(auth_object = nil)
    reflect_on_all_associations.map { |a| a.name.to_s } + _ransackers.keys
  end
end

app/models/article.rb
class Article < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]

  has_many :comments, dependent: :destroy
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 3 }

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user

  validates :body, presence: true, length: { minimum: 3, maximum: 50 }
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify

  after_create :assign_default_role

  has_many :articles, dependent: :destroy
  has_many :comments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable, :registerable

  def assign_default_role
    self.add_role(:reader) if self.roles.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  authorize_resource

  before_action :set_article, only: [:show, :edit,:update,:destroy]
  before_action :authenticate_user!, only: :show

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    article = current_user.articles.new(article_params)
    if article.save
      redirect_to articles_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to articles_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

    def article_params
      params.require(:article).permit(:title, :body, :user_id)
    end

    def set_article
      @article = Article.friendly.find(params[:id])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_article
  before_action :set_comment, only: :destroy

  def create
    comment = @article.comments.build(comment_params)
    comment.user = current_user
    if comment.save
      redirect_to article_path(@article)
    else
      render 'articles/show'
    end
  end

  def destroy
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
    def comment_params
      params.require(:comment).permit(:body)
    end

    def set_article
      @article = Article.friendly.find(params[:article_id])
    end

    def set_comment
      @comment = Comment.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<div class="container-fluid w-50 shadow mt-1 rounded border p-4 bg-secondary">
  <%= form_with model: article do |form| %>
    <% if article&.errors&.any? %>
      <div id="error_explanation">
        <h2 class="text-light "><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>
        <ul>
          <% article.errors.full_messages.each do |msg| %>
            <li class="text-light "><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-outline mb-4 ">
      <%= form.label :title, class: "form-label" %>
      <%= form.text_field :title, required: true, autofocus: true, autocomplete: "name", class: "form-control" %>
    </div>

    <div class="form-outline mb-4 ">
      <%= form.label :body, class: "form-label" %>
      <%= form.text_field :body, required: true, autofocus: true, autocomplete: "name", class: "form-control" %>
    </div>

    <% if current_admin_user %>
      <div class="form-outline mb-4 ">
        <%= form.select :user_id,options_for_select(User.with_role(:author).map { |u| [u.email, u.id] }), class: "form-control" %>
      </div>
    <% end %>

    <div class="form-outline mb-4 ">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/articles/edit.html.erb
<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<% if user_signed_in? %>
  <%= link_to "edit user", edit_user_registration_path, class: 'btn btn-sm btn-warning' %>
  <%= link_to "logout", destroy_user_session_path, data: {turbo_method: :delete}, class: 'btn btn-sm btn-danger' %>

  <h1>Articles</h1>

  <% @articles.each do |article| %>
    <div class="m-2 ">
      <ul class="list-group">
      <li class="list-group-item"><%= link_to article.title, article %></li>
      </ul>
    </div>
  <% end %>

  <% if current_user.has_role? :author %>
    <p><%= link_to "New Article", new_article_path , class: 'btn btn-sm btn-secondary text-dark' %></p>
  <% end %>
  
<% else %>
  <%= link_to "new user", new_user_registration_path, class: 'btn btn-sm btn-secondary text-dark mt-3' %>
  <%= link_to "login", new_user_session_path, class: 'btn btn-sm btn-secondary text-dark mt-3' %>
<% end %>

app/views/articles/new.html.erb
<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<p class="m-1 p-1"><strong>Title: </strong><%= @article.title %></p>
<p class="m-1 p-1"><strong>Body: </strong><%= @article.body %></p>

<% if @article.user == current_user and current_user.has_role? :author %>
  <%= link_to "Edit", edit_article_path(@article), class: 'btn btn-sm btn-primary' %>
  <%= link_to "Destroy", article_path(@article), data: {
                    turbo_method: :delete,
                    turbo_confirm: 'are you sure!!'
  }, class: 'btn btn-sm btn-primary' %>
<% end %>

<h2>Comments</h2>
<%= render 'comments/comment' %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

app/views/comments/_comment.html.erb
<% @article.comments.each do |comment| %>
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
    <% if comment.user == current_user %>
      <%= link_to "Destroy", article_comment_path(@article, comment), data: {
                    turbo_method: :delete,
                    turbo_confirm: 'are you sure!!'
                    }, class: 'btn btn-sm btn-primary' %>
    <% end %>
  </p>
<% end %>

app/views/comments/_form.html.erb
<div class="w-50 shadow mt-1 rounded border p-4 bg-secondary">
  <%= form_with model: [ @article, @article.comments.build ] do |form| %>
    <p>
      <% form.label :body %><br>
      <%= form.text_area :body %>
    </p>
    <p>
      <%= form.submit %>
    </p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoBlog2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if notice %>
      <div class="notice bg-secondary"><%= notice %></div>
    <% elsif alert %>
      <div class="alert alert-secondary"><%= alert %></div>
    <% end %>
    <% if user_signed_in? %>
      Logged in as: <%= current_user.email %>
    <% end %>
    <%= yield %>
  </body>
</html>